# Generated by Django 5.2.9 on 2025-12-12 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('surname', models.CharField(blank=True, max_length=50)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], max_length=10)),
                ('technologies', models.JSONField(default=list)),
                ('password', models.CharField(max_length=128)),
                ('dob', models.DateField()),
                ('resume', models.FileField(blank=True, null=True, upload_to='resumes/')),
                ('email', models.EmailField(max_length=254)),
                ('linkedin_url', models.URLField(blank=True, null=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('experience_years', models.PositiveIntegerField(default=0)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('job_locations', models.JSONField(default=list)),
                ('payment_done', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
