# Generated by Django 5.2.9 on 2025-12-14 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobregistration',
            name='password',
        ),
        migrations.RemoveField(
            model_name='jobregistration',
            name='payment_done',
        ),
        migrations.RemoveField(
            model_name='jobregistration',
            name='remarks',
        ),
    ]
