# Generated by Django 5.2.9 on 2025-12-14 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0002_remove_jobregistration_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobregistration',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobregistration',
            name='expected_salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='jobregistration',
            name='grade_or_percentage',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='jobregistration',
            name='highest_qualification',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jobregistration',
            name='notice_period',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='jobregistration',
            name='passing_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobregistration',
            name='portfolio_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobregistration',
            name='previous_companies',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='jobregistration',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobregistration',
            name='skills',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='jobregistration',
            name='university_or_college',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jobregistration',
            name='willing_to_relocate',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='jobregistration',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
