# Generated by Django 5.2.9 on 2025-12-14 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0003_jobregistration_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('surname', models.CharField(blank=True, max_length=50)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], max_length=10)),
                ('dob', models.DateField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('linkedin_url', models.URLField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('highest_qualification', models.CharField(blank=True, max_length=100, null=True)),
                ('university_or_college', models.CharField(blank=True, max_length=100, null=True)),
                ('passing_year', models.PositiveIntegerField(blank=True, null=True)),
                ('grade_or_percentage', models.CharField(blank=True, max_length=10, null=True)),
                ('technologies', models.JSONField(default=list)),
                ('job_locations', models.JSONField(default=list)),
                ('expected_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('resume', models.FileField(blank=True, null=True, upload_to='resumes/')),
                ('willing_to_relocate', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='JobRegistration',
        ),
    ]
